xcat2/xcat2.github.io

index.html
@bybai I am using an IDE Atom to make these changes and push it back up to the project. Still learning here... 
I still think that this is not very easy to use and make changes because the content is spread apart from each other..... but would like to see your thoughts. 
The whitespace changes in the diff, I will have to pay more attention to why this happened.  If it is just editor specific... doesn't seem to do any harm.
=> Update the content in the HPC box on the landing page

index.html, usecase.html
To cover: https://github.com/xcat2/xcat.org/issues/109
Changes:
- modify index.html to add use case summary and make it jump to new page `usecase.html`
- usecase.html (based on download.html) to add the 3 real case contents
Need a fixed width for the content of use cases page @bybai
=> modify the index.html to add usecase

download.html, index.html, usecase.html, webcontent/css/index.css
In publishing xcat.org webpage on line, I made some changes in online code including:
1. adjust css screen size
2. add google analytics account 
This task is to sync up xcat2.github.io code the same with xcat.org online code.
These code is tested by http://xcat.org
=> sync up new home page repo code with xcat.org online code

download.html, footer.html, index.html
update for xCAT 2.14.6 release
=> update for xCAT 2.14.6 release

download.html, footer.html, index.html, usecase.html, webcontent/css/default.css, webcontent/css/index.css
Merge master to stable branch for 2.14.6 release
=> Merge master to stable branch for 2.14.6 release 

head.html, index.html, joinus.html, sitemap.xml
https://github.ibm.com/xcat2/task_management/issues/77
https://github.com/xcat2/xcat2.github.io/issues/22
1. fix quickstart URL
2. create a page joinus.html to guide customer to select the proper channel
https://bybai.github.io/
=> create a page to guide customer to select the proper channel

.github/ISSUE_TEMPLATE/logo.md
Resolves #29 
@bybai i'll send you a private link to view what this  looks like... 
If this is merged, then you can update the link on the landing page to directly update
=> Add a logo template for users to opt-in/opt-out

index.html, webcontent/css/index.css, webcontent/js/index.js
###For tasks:
https://github.com/xcat2/xcat2.github.io/issues/36
https://github.com/xcat2/xcat2.github.io/issues/35
https://github.com/xcat2/xcat2.github.io/issues/34
###Descriptions:
add 3 customers stories and logos:
1. RedLine Performance Solutions, LLC
2. Versatus HPC
3. Stanford Research Computing Center
###UT:
1.
2.
3.
4.
5.
=> Add 3 customers stories and logos into xCAT home page

index.html
1. fix xCat to xCAT, 
2. add URL for Stanford Research Computing Center
=> fix xCat to xCAT

index.html, webcontent/js/index.js
For task: https://github.ibm.com/xcat2/task_management/issues/251
UT:
1. When mouse over or hand touch LRZ logo:
2. The default page
=> add LRZ logo and user case in xCAT home page

index.html, webcontent/js/index.js
sync up stable branch with master branch
=> add LRZ logo and user case

download.html
Ubuntu commands in codebox more formatting
=> Ubuntu commands in codebox2

download.html
Remove redundant sections and fix codeboxes
=> Ubuntu commands in codebox3

download.html
=> Ubuntu commands in codebox4

download.html
=> Ubuntu commands in codebox5

index.html
=> [Logo] Add OCF logo

webcontent/js/index.js
=> OCF description

webcontent/js/index.js
Display ocf description on mouseover
=> Display ocf description on mouseover

backup/cleanup_snapshot_files.py
Preseve last snapshot file of its kind, even if it is older than cutoff date
=> Preseve last snapshot file of its kind

backup/runbackup
This should be exceuted as a cronjob., seems like the backup was not happening since Nov 2018, so I'm trying to re-enable it...
=> Backup script requires changes after being moved from xcat.org to this repo. 

backup/cleanup_snapshot_files.py, backup/runcleanup
Script to run cleanup_snapshot_files.py from c910 login node
=> Script to run cleanup_snapshot_files.py from login node

backup/cleanup_snapshot_files.py
Added debug and dryrun options as suggested in the review.
Did not use `docopt`, since they are not available on `xcat.org`.
=> Add debug and dryrun options

download.html
Point to installation instruction on read the docs
=> Add installation steps to download page

download.html, footer.html
Break up existing `xcat-dep` section into stable and devel sections.
=> Break xcat-dep section into stable and devel

download.html
Fix some formatting problems with download page
=> Download page formatting

download.html
Add some horizontal rulers for separation
=> Download page formatting 2

promote_build.py
This PR completes the remaining issue raised by https://github.com/xcat2/xcat-core/issues/3322
* Fix `xcat-dep.repo` file when it is moved from `yum/devel/xcat-dep/` to `yum/xcat-dep/` by removing `devel` in the path. The `devel` is inserted into the path by `builddep.sh` script when `xcat-dep` is uploaded to `xcat.org` (https://github.com/xcat2/xcat-core/pull/6444)
* Create link for `files/xcat/xcat-dep/2.x_Linux/xcat-dep-<version>-linux.tar.bz2` to `xcat-dep-<timestamp>.tar.bz2` with the latest timestamp
* Create link for `files/xcat/xcat-dep/2.x_Linux/xcat-dep-ubuntu<version>-linux.tar.bz2` to `xcat-dep-ubuntu-<timestamp>.tar.bz2` with the latest timestamp
Before build promotion, manually created skeleton of some of the files involved:
```
.
├── files
│   └── xcat
│       ├── repos
│   …
```
=> Automate more of build promotion

download.html, index.html
Update `xcat.org` files for 2.15 release.
=> Update links for 2.15 release

download.html
Add notice for BMC password expiration
=> BMC change password notice

download.html
=> Formatting changes to BMC change pw notice

download.html
=> Formatting changes to BMC change pw notice2

index.html
For issue #88 
Chrome and Safari incorrectly display BSC logo.
=> Fix size of logos

index.html
Cineca logo has changed.
Point to the new logo in the new location.
=> Replace CINECA logo image

index.html
Change Cineca logo background.
=> Fix Cineca logo background

index.html, webcontent/js/index.js
Add University of San Diego logo.
=> U of San Diego logo

index.html
Need to fixed size for Chrome browsers.
=> Fix CINECA logo for Chrome browser

download.html, footer.html, index.html
=> Update links for 2.15.1 release

index.html
=> Bump out 2.15.1 release date

index.html, webcontent/js/index.js
=> Add Corehive logo

webcontent/js/index.js
=> Corehive missing bracket

index.html
=> Location of OCF logo moved

download.html, footer.html, index.html
=> Update for 2.16.1 release

backup/runbackup
Remove Casandra, add Peter for xcat.org backup report.
=> Update email list for backup report

index.html
Adding Planned archival notice to the home page
=> Planned archival notice

index.html
=> Planned archival notice2

index.html
=> Planned archival notice3

index.html
=> Planned archival notice4
